export const ICON_NAMES = {
    SYSTEM_ICONS: {
        ACCOUNTS: 'ACCOUNTS',
        CASHFLOW: 'CASHFLOW',
        CATEGORIES: 'CATEGORIES',
        DASHBOARD: 'DASHBOARD',
        EDUCATION: 'EDUCATION',
        PROFILE: 'PROFILE',
        SETTINGS: 'SETTINGS',
        TRANSACTIONS: 'TRANSACTIONS',
        ADD: 'ADD',
        ADD_ACCOUNT: 'ADD_ACCOUNT',
        ADD_TRANSFER: 'ADD_TRANSFER',
        BACK: 'BACK',
        DROPDOWN: 'DROPDOWN',
        DOWNLOAD: 'DOWNLOAD',
        EDIT: 'EDIT',
        HISTORY: 'HISTORY',
        NOTIFICATIONS: 'NOTIFICATIONS',
        REFRESH: 'REFRESH',
        RECEIVE_MONEY: 'RECEIVE_MONEY',
        SEARCH: 'SEARCH',
        SEND_MONEY: 'SEND_MONEY',
        TIME: 'TIME'
    },

    ACCOUNT_ICONS: {
        BANK: 'BANK',
        CREDIT_CARD: 'CREDIT_CARD',
        WALLET: 'WALLET',
        RECEIPT: 'RECEIPT',
        LIGHTBULB: 'LIGHTBULB',
        PAPER_MONEY: 'PAPER_MONEY',
        SAFE_SHIELD: 'SAFE_SHIELD',
        MONETIZATION: 'MONETIZATION',
        PERCENTAGE: 'PERCENTAGE',

        AUB: 'AUB',
        BANCNET: 'BANCNET',
        BDO: 'BDO',
        BPI: 'BPI',
        CHINABANK: 'CHINABANK',
        CITIBANK: 'CITIBANK',
        EASTWEST: 'EASTWEST',
        GCASH: 'GCASH',
        // LANDBANK: 'LANDBANK',
        MASTERCARD: 'MASTERCARD',
        // MAYBANK: 'MAYBANK',
        METROBANK: 'METROBANK',
        PAYMAYA: 'PAYMAYA',
        PAYPAL: 'PAYPAL',
        PNB: 'PNB',
        PSBANK: 'PSBANK',
        ROBINSONSBANK: 'ROBINSONSBANK',
        SECURITYBANK: 'SECURITYBANK',
        UNIONBANK: 'UNIONBANK'
    },

    CATEGORY_ICONS: {
        //TRANSPORTATION
        AIRLINE_FARE: 'AIRLINE_FARE',
        BICYCLE: 'BICYCLE',
        BOAT: 'BOAT',
        BUSFARE: 'BUSFARE',
        CAR: 'CAR',
        CARWASH: 'CARWASH',
        CAR_REPAIR: 'CAR_REPAIR',
        EV_STATION: 'EV_STATION',
        GAS_STATION: 'GAS_STATION',
        MOTORCYCLE: 'MOTORCYCLE',
        PARKING: 'PARKING',
        SCOOTER: 'SCOOTER',
        SUBWAY: 'SUBWAY',
        TAXI: 'TAXI',
        TRAINFARE: 'TRAINFARE',

        //SHOPPING
        APPLIANCES: 'APPLIANCES',
        CAMERA: 'CAMERA',
        CLOTHES: 'CLOTHES',
        ELECTRONICS: 'ELECTRONICS',
        FLOWERS: 'FLOWERS',
        GAMING: 'GAMING',
        GIFT: 'GIFT',
        GROCERY: 'GROCERY',
        JEWELRY: 'JEWELRY',
        LAPTOP: 'LAPTOP',
        PHONE: 'PHONE',
        PRICE_TAG: 'PRICE_TAG',
        SHOP: 'SHOP',
        SHOPPING_BAG: 'SHOPPING_BAG',
        TOYS: 'TOYS',
        WATCH: 'WATCH',

        //FOOD
        BEER: 'BEER',
        BREAD: 'BREAD',
        BURGER: 'BURGER',
        CAKE: 'CAKE',
        COOKIE: 'COOKIE',
        FISH: 'FISH',
        FOOD: 'FOOD',
        HONEY: 'HONEY',
        ICECREAM: 'ICECREAM',
        LIQUOR: 'LIQUOR',
        PIZZA: 'PIZZA',

        //HOME
        AIRCON: 'AIRCON',
        APARTMENT: 'APARTMENT',
        BATHROOM: 'BATHROOM',
        CLEANING: 'CLEANING',
        DEVICES: 'DEVICES',
        ELECTRICITY_BILLS: 'ELECTRICITY_BILLS',
        FURNITURE: 'FURNITURE',
        GARDEN: 'GARDEN',
        GAS: 'GAS',
        GRILL: 'GRILL',
        HARDWARE: 'HARDWARE',
        HOUSE: 'HOUSE',
        INTERNET_BILLS: 'INTERNET_BILLS',
        KEYS: 'KEYS',
        LIGHTS: 'LIGHTS',
        MAINTENANCE: 'MAINTENANCE',
        PAINT: 'PAINT',
        SANITIZER: 'SANITIZER',
        SUBSCRIPTIONS: 'SUBSCRIPTIONS',
        TV: 'TV',
        WATER_BILLS: 'WATER_BILLS',

        //HEALTH
        FITNESS: 'FITNESS',
        HEALTH: 'HEALTH',
        HEALTH_MONITOR: 'HEALTH_MONITOR',
        MEDICAL_KIT: 'MEDICAL_KIT',
        MEDICATION: 'MEDICATION',
        PERSONAL_CARE: 'PERSONAL_CARE',
        PSYCHOLOGY: 'PSYCHOLOGY',
        VACCINE: 'VACCINE',

        //Entertainment
        BAR: 'BAR',
        PARTY: 'PARTY',
        CASINO: 'CASINO',
        FINE_DINING: 'FINE_DINING',
        MOVIES: 'MOVIES',
        MUSIC: 'MUSIC',
        NIGHTCLUB: 'NIGHTCLUB',
        ROOM_SERVICE: 'ROOM_SERVICE',
        SPORTS_STADIUM: 'SPORTS_STADIUM',
        THEATRE: 'THEATRE',

        //Activities
        BASKETBALL: 'BASKETBALL',
        BIKING: 'BIKING',
        KAYAKING: 'KAYAKING',
        RUNNING: 'RUNNING',
        SWIMMING: 'SWIMMING',
        DIVING: 'DIVING',
        SKIING: 'SKIING',
        KITE_SURFING: 'KITE_SURFING',
        ROWING: 'ROWING',
        SKATEBOARDING: 'SKATEBOARDING',
        SLEDDING: 'SLEDDING',
        SNOWBOARDING: 'SNOWBOARDING',
        SURFING: 'SURFING',
        PARAGLIDING: 'PARAGLIDING',
        MEDITATION: 'MEDITATION',

        //Relaxation
        BEACH: 'BEACH',
        SUNSET: 'SUNSET',
        MOUNTAIN: 'MOUNTAIN',
        HOUSE_BOAT: 'HOUSE_BOAT',
        LUGGAGE: 'LUGGAGE',
        HOLIDAY_CABIN: 'HOLIDAY_CABIN',

        //Education
        EDUCATION: 'EDUCATION',
        SCHOOL_SUPPLIES: 'SCHOOL_SUPPLIES',
        BOOKS: 'BOOKS',

        //Family
        PETS: 'PETS',
        STROLLER: 'STROLLER',
        CHILD_CARE: 'CHILD_CARE',
        BABY_TOYS: 'BABY_TOYS',
        CRIB: 'CRIB',
        FAMILY: 'FAMILY',

        //Other
        OTHER_QUESTION: 'OTHER_QUESTION',
        OTHER_INFO: 'OTHER_INFO',
        OTHER_STAR: 'OTHER_STAR',
        SMOKING: 'SMOKING',
        VAPING: 'VAPING',

        //Priority
        BUSINESS: 'BUSINESS',
        FREELANCE_JOB: 'FREELANCE_JOB',
        FULLTIME_JOB: 'FULLTIME_JOB',
        SAVINGS: 'SAVINGS',
        REDEEMS: 'REDEEMS',
        CRYPTO: 'CRYPTO'
    }
};
